import React from 'react';
import { Sprout, Sparkles } from 'lucide-react';
import CropPredictionCard from './CropPredictionCard';
import SoilHealthChart from './SoilHealthChart';
import WeatherImpactChart from './WeatherImpactChart';
import RecommendationsCard from './RecommendationsCard';

function PredictionResults({ prediction, loading }) {
  
  // --- EXPORT FUNCTIONS ---
  const handleDownloadPDF = (prediction) => {
    if (!prediction) return;
    
    // Safety check for recommendations
    const irrigation = prediction.recommendations?.irrigation || [];
    const fertilization = prediction.recommendations?.fertilization || [];
    const pestControl = prediction.recommendations?.pestControl || [];

    const reportContent = `
===========================================
    AI CROP CROP PREDICTION REPORT
===========================================

PREDICTION SUMMARY:
-------------------------------------------
Current Crop:      ${prediction.currentCrop} ${prediction.unit}
Optimized Crop:    ${prediction.optimizedCrop} ${prediction.unit}
Improvement:        +${prediction.improvement}%

RECOMMENDATIONS:
-------------------------------------------

IRRIGATION:
${irrigation.map((r, i) => `${i + 1}. ${r}`).join('\n')}

FERTILIZATION:
${fertilization.map((r, i) => `${i + 1}. ${r}`).join('\n')}

PEST CONTROL:
${pestControl.map((r, i) => `${i + 1}. ${r}`).join('\n')}

===========================================
Generated by AI Crop Prediction Platform
Date: ${new Date().toLocaleDateString()}
===========================================
    `;

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `crop-crop-report-${new Date().getTime()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
    
    alert('✅ Report downloaded successfully!');
  };

  const handleShare = (prediction) => {
    if (!prediction) return;
    const shareText = `Check out my crop crop prediction! 🌾\n\nCurrent Crop: ${prediction.currentCrop} ${prediction.unit}\nOptimized Crop: ${prediction.optimizedCrop} ${prediction.unit}\nImprovement: +${prediction.improvement}%\n\nGenerated by AI Crop Prediction Platform`;
    
    if (navigator.share) {
      navigator.share({
        title: 'Crop Crop Prediction',
        text: shareText,
      }).then(() => console.log('Shared successfully'))
        .catch((error) => {
          console.log('Error sharing:', error);
          fallbackShare(shareText);
        });
    } else {
      fallbackShare(shareText);
    }
  };

  const fallbackShare = (text) => {
    navigator.clipboard.writeText(text).then(() => {
      alert('✅ Results copied to clipboard!');
    }).catch(() => {
      alert('Unable to share. Please copy manually.');
    });
  };

  const handleSaveReport = (prediction) => {
    if (!prediction) return;
    const report = {
      date: new Date().toISOString(),
      prediction: prediction,
      timestamp: Date.now()
    };
    
    try {
      const savedReports = JSON.parse(localStorage.getItem('cropYieldReports') || '[]');
      savedReports.push(report);
      localStorage.setItem('cropYieldReports', JSON.stringify(savedReports));
      alert('✅ Report saved successfully!');
    } catch (error) {
      alert('❌ Unable to save report.');
    }
  };

  // --- 1. LOADING STATE ---
  if (loading) {
    return (
      <div className="bg-white rounded-2xl shadow-2xl p-12 text-center animate-scaleIn">
        <div className="flex flex-col items-center justify-center space-y-6">
          <div className="relative">
            <div className="w-24 h-24 border-8 border-green-200 border-t-green-600 rounded-full animate-spin"></div>
            <Sprout className="w-10 h-10 text-green-600 absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 animate-pulse" />
          </div>
          
          <div className="space-y-2">
            <h3 className="text-2xl font-bold text-gray-800">Analyzing Your Farm Data...</h3>
            <p className="text-gray-600">Our AI is processing soil, weather, and crop parameters</p>
          </div>

          <div className="w-full max-w-md space-y-3">
            {['Analyzing soil composition', 'Processing weather data', 'Calculating crop predictions', 'Generating recommendations'].map((step, index) => (
              <div key={index} className="flex items-center space-x-3 animate-fadeIn" style={{ animationDelay: `${index * 0.3}s` }}>
                <div className="w-2 h-2 bg-green-500 rounded-full animate-pulse"></div>
                <span className="text-sm text-gray-600">{step}</span>
              </div>
            ))}
          </div>

          <div className="w-full max-w-md">
            <div className="h-2 bg-gray-200 rounded-full overflow-hidden">
              <div className="h-full bg-gradient-to-r from-green-500 via-emerald-500 to-teal-500 animate-shimmer"></div>
            </div>
          </div>
        </div>
      </div>
    );
  }

  // --- 2. EMPTY STATE (No Prediction) ---
  if (!prediction) {
    return (
      <div className="bg-gradient-to-br from-white to-green-50 rounded-2xl shadow-2xl p-12 text-center relative overflow-hidden animate-scaleIn">
        <div className="absolute top-0 left-0 w-32 h-32 bg-green-200 rounded-full mix-blend-multiply filter blur-xl opacity-20 animate-blob"></div>
        <div className="absolute bottom-0 right-0 w-40 h-40 bg-emerald-200 rounded-full mix-blend-multiply filter blur-xl opacity-20 animate-blob animation-delay-2000"></div>
        
        <div className="relative z-10">
          <div className="inline-flex p-6 bg-gradient-to-br from-green-500 to-emerald-600 rounded-3xl mb-6 shadow-2xl float-animation">
            <Sprout className="w-16 h-16 text-white" />
          </div>
          
          <h3 className="text-3xl font-bold text-gray-800 mb-3 flex items-center justify-center">
            <Sparkles className="w-6 h-6 text-yellow-500 mr-2" />
            Enter Farm Details
          </h3>
          
          <p className="text-gray-600 mb-8 max-w-lg mx-auto leading-relaxed">
            Fill in the form on the left to receive AI-powered crop predictions and recommendations.
          </p>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 max-w-2xl mx-auto mb-8">
            {[
              { icon: '🎯', text: 'Accurate AI Predictions' },
              { icon: '📊', text: 'Visual Analytics' },
              { icon: '💡', text: 'Smart Recommendations' },
              { icon: '🌦️', text: 'Weather Integration' }
            ].map((feature, index) => (
              <div 
                key={index} 
                className="flex items-center space-x-3 bg-white p-4 rounded-xl shadow-md hover:shadow-lg transition-all transform hover:-translate-y-1 animate-fadeIn"
                style={{ animationDelay: `${index * 0.1}s` }}
              >
                <span className="text-2xl">{feature.icon}</span>
                <span className="text-sm font-medium text-gray-700">{feature.text}</span>
              </div>
            ))}
          </div>

          <div className="flex items-center justify-center space-x-2 text-green-600 animate-bounce">
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 11l5-5m0 0l5 5m-5-5v12" />
            </svg>
            <span className="text-sm font-semibold">Fill the form to start</span>
          </div>
        </div>
      </div>
    );
  }

  // --- 3. SUCCESS STATE (Results) ---
  return (
    <div className="space-y-6">
      <div className="bg-gradient-to-r from-green-500 to-emerald-600 text-white px-6 py-3 rounded-xl shadow-lg flex items-center justify-center space-x-2 animate-fadeIn">
        <Sparkles className="w-5 h-5" />
        <span className="font-semibold">Prediction Complete! Here are your results:</span>
      </div>

      {/* Main Results Cards */}
      <div className="animate-fadeIn" style={{ animationDelay: '0.1s' }}>
        <CropPredictionCard prediction={prediction} language="en" />
      </div>
      
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="animate-fadeIn" style={{ animationDelay: '0.2s' }}>
          <SoilHealthChart data={prediction.soilHealth} language="en" />
        </div>
        <div className="animate-fadeIn" style={{ animationDelay: '0.3s' }}>
          <WeatherImpactChart data={prediction.weatherImpact} language="en" />
        </div>
      </div>
      
      <div className="animate-fadeIn" style={{ animationDelay: '0.4s' }}>
        <RecommendationsCard recommendations={prediction.recommendations} language="en" />
      </div>

      {/* Export Options */}
      <div className="bg-white rounded-2xl shadow-lg p-6 animate-fadeIn" style={{ animationDelay: '0.5s' }}>
        <h3 className="text-lg font-bold text-gray-800 mb-4">Export Your Results</h3>
        <div className="flex flex-wrap gap-3">
          <button 
            onClick={() => handleDownloadPDF(prediction)}
            className="flex-1 min-w-[150px] bg-blue-50 hover:bg-blue-100 text-blue-700 font-semibold py-3 px-4 rounded-xl transition-all transform hover:-translate-y-1 flex items-center justify-center space-x-2 hover:shadow-lg"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z" />
            </svg>
            <span>Download PDF</span>
          </button>
          <button 
            onClick={() => handleShare(prediction)}
            className="flex-1 min-w-[150px] bg-green-50 hover:bg-green-100 text-green-700 font-semibold py-3 px-4 rounded-xl transition-all transform hover:-translate-y-1 flex items-center justify-center space-x-2 hover:shadow-lg"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z" />
            </svg>
            <span>Share Results</span>
          </button>
          <button 
            onClick={() => handleSaveReport(prediction)}
            className="flex-1 min-w-[150px] bg-purple-50 hover:bg-purple-100 text-purple-700 font-semibold py-3 px-4 rounded-xl transition-all transform hover:-translate-y-1 flex items-center justify-center space-x-2 hover:shadow-lg"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7H5a2 2 0 00-2 2v9a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-3m-1 4l-3 3m0 0l-3-3m3 3V4" />
            </svg>
            <span>Save Report</span>
          </button>
        </div>
      </div>
    </div>
  );
}

export default PredictionResults;